### ISSUE TITLE
Adding cmd-line options for salmon via yaml doesn't work

### ISSUE THREAD

**Issue by Nicolai-vKuegelgen** [BIMSBbioinfo/pigx_rnaseq#68]
The "tools" section of the yaml file is supposed to allow customisation of cmd-line options, however this doesn't work properly for salmon due to 2 reasons:

1) salmon quant & salmon index use the same tool entry (whereas star_map and star_index have separate entries); most cmd options only apply to one of the two salmon usages and will fail if applied to both.

2) Compared to STAR the options for salmon need to go *after* the first subargument, i.e.: salmon quant {options}. To make the cmd-line options customisable with the current setup of the pipeline the quant / index part of the command needs to move from the rule definition to the executable (or args) part of the settings file.

Proposed solution:

```
tools:
   salmon:
    executable: @SALMON@
    args: ""
```
becomes: 
```
tools:
   salmon_index:
    executable: "@SALMON@ index"
    args: ""
  salmon_quant:
    executable: "@SALMON@ quant"
    args: ""
```
